# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 21, 45, 52, 14000, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
