# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='item',
        ),
    ]
