# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20160313_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=260),
        ),
    ]
